# 基礎題

## 1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

In [3]:
import numpy as np

a = np.arange(12).reshape(3,4)

print('type(a): ', type(a), '  # type() 返回資料型別')
print('a.dtype: ', a.dtype, '  # dtype 返回陣列中元素的資料型別')

type(a):  <class 'numpy.ndarray'>   # type() 返回資料型別
a.dtype:  int64   # dtype 返回陣列中元素的資料型別




## 2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式，並且通過測試。

In [5]:
def is_dtype(a, t):
    return a.dtype == t
    
a = np.random.randint(10, size=6) 

# 測試一
print(is_dtype(a, 'int')) # True

# 測試二
print(is_dtype(a, np.int)) # True

# 測試三
print(is_dtype(a, np.dtype('int'))) # True

True
True
True




## 3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？
```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

In [10]:
def is_dtype(a, t):
    return a.dtype is t

a = np.random.randint(10, size=6) 

print(is_dtype(a, 'int'))
print('a.dtype:', a.dtype)
print('t:', 'int')

False
a.dtype: int64
t: int


因為 is 為強比較，必須兩方規格都相同。

In [9]:
def is_dtype(a, t):
    return type(a) == np.dtype(t)

a = np.random.randint(10, size=6) 

print(is_dtype(a, 'int'))
print('type(a):', type(a))
print('np.dtype(t):', np.dtype('int'))

False
type(a): <class 'numpy.ndarray'>
np.dtype(t): int64


type(a) 是整個陣列的資料型別，np.dtype(t) 是元素的物件屬性。

In [11]:
def is_dtype(a, t):
    return type(a) is np.dtype(t)

a = np.random.randint(10, size=6) 

print(is_dtype(a, 'int'))
print('type(a):', type(a))
print('np.dtype(t):', np.dtype('int'))

False
type(a): <class 'numpy.ndarray'>
np.dtype(t): int64


同上，type(a) 是整個陣列的資料型別，np.dtype(t) 是元素的物件屬性。

---

# 進階題

題目：
array1 = np.array(range(30))
1. 將上列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")
2. 呈上題的 array，找出被 6 除餘 1 的數的索引

In [13]:
array1 = np.array(range(30))

array2 = np.reshape(array1, (5,6), order='F')

print('Before:', array1)
print('After:', array2)

Before: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
After: [[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [16]:
np.where(array2 % 6 == 1)

(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))