In [1]:
import numpy as np

---


# 基礎題

## 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？
```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

In [5]:
a = np.arange(15).reshape(3, 5)
print('list(a):', list(a))
print(type(list(a)))
print(type(list(a)[0]))
print('')
print('tolist():', a.tolist())
print(type(a.tolist()))
print(type(a.tolist()[0]))

list(a): [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
<class 'list'>
<class 'numpy.ndarray'>

tolist(): [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
<class 'list'>
<class 'list'>


list(a) 與 a.tolist() 的輸出皆為 list 型態。
list(a) 只在第一個維度進行迭代輸出一個列表，而 a.tolist() 將陣列全部轉換為列表型態，可以看到第二維度也是 list。



## 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）
```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [6]:
a = np.random.randint(10, size=6)
print(a)
# ndim、shape、size、dtype、itemsize、length、type
print('ndim:',a.ndim) # 1
print('shape:', a.shape) # (6,)
print('size:', a.size) # 6
print('dtype:', a.dtype) # int64
print('itemsize:', a.itemsize) # 8
print('length:', len(a)) # 6
print('type:', type(a)) # ndarray

[0 6 4 3 7 9]
ndim: 1
shape: (6,)
size: 6
dtype: int64
itemsize: 8
length: 6
type: <class 'numpy.ndarray'>


In [7]:
b = np.random.randint(10, size=(3,4))
print(b)
# ndim、shape、size、dtype、itemsize、length、type
print('ndim:', b.ndim) # 2
print('shape:', b.shape) # (3,4)
print('size:', b.size) # 12
print('dtype:', b.dtype) # int64
print('length:', len(b)) # 3
print('type:', type(b)) # ndarray

[[1 5 5 7]
 [6 7 0 8]
 [3 6 4 1]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int64
length: 3
type: <class 'numpy.ndarray'>


In [8]:
c = np.random.randint(10, size=(2,3,2))
print(c)
# ndim、shape、size、dtype、itemsize、length、type
print('ndim:', c.ndim) # 3
print('shape:', c.shape) # (2,3,2)
print('size:', c.size) # 12
print('dtype:', c.dtype) # int64
print('length:', len(c)) # 2
print('type:', type(c)) # ndarray

[[[3 0]
  [7 2]
  [8 2]]

 [[0 5]
  [5 6]
  [2 4]]]
ndim: 3
shape: (2, 3, 2)
size: 12
dtype: int64
length: 2
type: <class 'numpy.ndarray'>




## 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

In [9]:
a = np.random.randint(10, size=6) 

print('a.tolist():', a.tolist())
print('list(a):', list(a))

print('')

b = np.random.randint(10, size=(3,4)) 

print('b.tolist():', b.tolist())
print('list(b):', list(b))

print('')

c = np.random.randint(10, size=(2,3,2)) 

print('c.tolist():', c.tolist())
print('list(c):', list(c))

a.tolist(): [8, 7, 7, 7, 6, 2]
list(a): [8, 7, 7, 7, 6, 2]

b.tolist(): [[1, 8, 9, 3], [1, 3, 7, 6], [8, 4, 2, 9]]
list(b): [array([1, 8, 9, 3]), array([1, 3, 7, 6]), array([8, 4, 2, 9])]

c.tolist(): [[[7, 8], [1, 7], [1, 5]], [[3, 4], [2, 2], [2, 3]]]
list(c): [array([[7, 8],
       [1, 7],
       [1, 5]]), array([[3, 4],
       [2, 2],
       [2, 3]])]


In [10]:
def list(iterable):
    return iterable.tolist()

print('list(a) -> a.tolist:', list(a))
print('list(b) -> b.tolist:', list(b))
print('list(c) -> c.tolist:', list(c))

list(a) -> a.tolist: [8, 7, 7, 7, 6, 2]
list(b) -> b.tolist: [[1, 8, 9, 3], [1, 3, 7, 6], [8, 4, 2, 9]]
list(c) -> c.tolist: [[[7, 8], [1, 7], [1, 5]], [[3, 4], [2, 2], [2, 3]]]


---


# 延伸題
題目:
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
2.呈上題，將以上數列取出偶數。
3.呈1題，將數列取出3的倍數。

In [11]:
a = np.arange(21)
print (a)

print('')

b = a[0:21:2]
print (b)

print('')

c = a[0:21:3]
print (c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[ 0  2  4  6  8 10 12 14 16 18 20]

[ 0  3  6  9 12 15 18]
