# 基礎題

## 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

In [1]:
import numpy as np

print('np.zeros:', np.zeros((2, 3)))
print('np.empty:', np.empty((2, 3)))

np.zeros: [[0. 0. 0.]
 [0. 0. 0.]]
np.empty: [[0. 0. 0.]
 [0. 0. 0.]]


np.zeros 與 np.empty 生成的陣列皆由 0 組成，差別在 np.empty 的數值是接近 0 的隨機數。



## 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

In [2]:
# 使用 np.around 四捨五入

a = np.random.rand(2, 3) * 100
print(a)

b = np.around(a)
print(b)

[[ 4.58423634 39.52566876 49.63018616]
 [62.23538151 88.12775272 51.18384422]]
[[ 5. 40. 50.]
 [62. 88. 51.]]




## 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [3]:
a = np.random.rand(2, 3) * (20)
b = a

print((a - b % 1) + 20)

[[34. 36. 28.]
 [32. 21. 37.]]


# 延伸題

題目：
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]


## 1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]

In [16]:
dt = np.dtype({'names':('name', 'sex', 'weight', 'rank', 'myopia'), 'formats':('U5', 'U5', float, int, bool)})
c = np.zeros(8, dtype=dt)
c

array([('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False)],
      dtype=[('name', '<U5'), ('sex', '<U5'), ('weight', '<f8'), ('rank', '<i8'), ('myopia', '?')])

In [17]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

c['name'] = name_list
c['sex'] = sex_list
c['weight'] = weight_list
c['rank'] = rank_list
c['myopia'] = myopia_list
print(c)

[('小明', 'boy', 67.5, 8,  True) ('小華', 'boy', 75.3, 1,  True)
 ('小菁', 'girl', 50.1, 5, False) ('小美', 'girl', 45.5, 4, False)
 ('小張', 'boy', 80.8, 7,  True) ('John', 'boy', 90.4, 6,  True)
 ('Mark', 'boy', 78.4, 2, False) ('Tom', 'boy', 70.7, 3, False)]



## 2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重

In [18]:
np.mean(c['weight'])

69.8375


## 3. 呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重

In [26]:
print('男生平均體重: ', np.mean(c[c['sex'] == 'boy']['weight']))
print('女生平均體重: ', np.mean(c[c['sex'] == 'girl']['weight']))

男生平均體重:  77.18333333333332
女生平均體重:  47.8
