# 基礎題

## 1. [簡答題] 請問下列程式碼，運算結果分別為何？

a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] )

In [1]:
import numpy as np

a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] )

In [2]:
print('a + a:', a + a) # [40, 60, 80, 100]
print('a + b:', a + b) # [21, 32, 43, 54]
print('a + c:', a + c) # [21, 31, 41, 51]
print('a + d:', a + d) # [21, 31, 41, 51]
print('a + e:', a + e) # 因 a 與 e 陣列的大小不一樣，所以無法進行運算

a + a: [ 40  60  80 100]
a + b: [21 32 43 54]
a + c: [21 31 41 51]
a + d: [21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

若將 e 由 1X2 改為 2X1 陣列，將可以與 a 進行加法運算。

In [3]:
e_test = np.array( [[1], [2]] )
print('a + e_test:', a + e_test)

a + e_test: [[21 31 41 51]
 [22 32 42 52]]



## 2. 如何在不用迴圈的情況下計算 (A+B) * (-A/2) ？那用迴圈怎麼做？

In [4]:
A = np.ones(3)*1
B = np.ones(3)*2

print('直接算:')
print( (A + B) * (-A / 2) )

直接算:
[-1.5 -1.5 -1.5]


In [5]:
print('迴圈:')

c = []
for i in A:
    c.append( (i + i * 2) * (-i / 2) )
print(c)

迴圈:
[-1.5, -1.5, -1.5]



## 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

In [11]:
A = np.ones((1,6))
B = np.ones((6,1))
print(A)
print(B)

print('---------------')

print('內積: np.dot(A, B) = ', np.dot(A, B))
print('外積: np.outer(A, B) = ', np.outer(A, B))

[[1. 1. 1. 1. 1. 1.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
---------------
內積: np.dot(A, B) =  [[6.]]
外積: np.outer(A, B) =  [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
