## 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。

In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 12)

arr1 = arr
arr1[2:6] = -arr[2:6]
print(arr1)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


## 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？

In [3]:
A = np.random.rand(3, 6)
print(A)

[[0.29180574 0.9267597  0.22853548 0.95640046 0.8186018  0.19049719]
 [0.23257385 0.93444509 0.46979289 0.72648829 0.98697084 0.21743295]
 [0.80981457 0.75224296 0.57302837 0.90092649 0.94304953 0.87643647]]


In [4]:
print(A[A > 0.5].size)

12
